version: '3.8'

services:
  csvserver:
    image: infracloudio/csvserver:latest
    volumes:
      - ./inputFile:/csvserver/inputdata
    environment:
      - CSVSERVER_BORDER=Orange
    ports:
      - "9393:9300"
    env_file:
      - csvserver.env
      
  prometheus:
    image: prom/prometheus:v2.45.2
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
