version: '3.8'

services:
  csvserver:
    image: infracloudio/csvserver:latest
    volumes:
      - ./inputFile:/csvserver/inputdata
    environment:
      - CSVSERVER_BORDER=Orange
    ports:
      - "9393:9300"
    env_file:
      - csvserver.env

